### STAGE 1: Build ###

FROM node:lts-bullseye AS build

WORKDIR /usr/src/app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

### STAGE 2: Run ###
FROM nginx:1.26.0-bookworm

COPY --from=build /usr/src/app/dist/wis_frontend /usr/share/nginx/html
