### STAGE 1: Build ###

FROM node:lts-bullseye AS build

WORKDIR /usr/src/app
COPY package.json ./
RUN npm install -g npm@10.8.2
RUN npm install
COPY . .
RUN npm run build

### STAGE 2: Run ###
FROM nginx:stable

COPY --from=build /usr/src/app/dist/wis_frontend /usr/share/nginx/html
