version: '3.8'
services:
  nginx:
    build:
      context: frontend
    ports:
      - 7070:80
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx/
    links:
      - django

  django:
    build:
      context: backend
    command: gunicorn wis_backend.wsgi:application --bind 0.0.0.0:1337 --workers=3
    volumes:
      - ./backend/db.sqlite3:/home/app/web/db.sqlite3
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 1337
    env_file:
      - ./.env
    
volumes:
  static_volume:
  media_volume:
  