services:
  web:
    build:
      context: ./app
      dockerfile: dockerfile.prod
    command: gunicorn WeatherInSight.wsgi:application --bind 0.0.0.0:1337 --worker=3
    volumes:
      - ./app/db.sqlite3:/home/app/web/db.sqlite3
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:1337
    env_file:
      - ./.env.prod

volumes:
  static_volume:
  media_volume:
