# Pull Official base image
FROM python:bullseye

# set Working Dir
WORKDIR /usr/src/app

# set ENV
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYHTONUNBUFFERED 1

# Install dependancies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# Copy Project
COPY . .